# Generated by Django 4.1.1 on 2023-01-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='suma',
            field=models.FloatField(default=0, help_text='Iveskite paslaugos kaina', max_length=10, verbose_name='Suma'),
        ),
        migrations.AddField(
            model_name='uzsakymoeilute',
            name='kaina',
            field=models.FloatField(default=0, help_text='Iveskite paslaugos kaina', max_length=10, verbose_name='Kaina'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='vin_kodas',
            field=models.CharField(help_text='Iveskite VIN numeri', max_length=17, verbose_name='VIN kodas'),
        ),
        migrations.AlterField(
            model_name='paslauga',
            name='kaina',
            field=models.FloatField(help_text='Iveskite paslaugos kaina', max_length=10, verbose_name='Kaina'),
        ),
    ]
