# Generated by Django 4.1.1 on 2023-01-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0003_alter_automobilis_options_alter_modelis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='automobilis_pic',
            field=models.ImageField(blank=True, null=True, upload_to='car_pics', verbose_name='Auto Nuotrauka'),
        ),
    ]
