# Generated by Django 4.1.1 on 2023-01-23 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservisas', '0004_automobilis_automobilis_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymoeilute',
            name='grazinti_iki',
            field=models.DateField(blank=True, null=True, verbose_name='Pabaigti darbus iki: '),
        ),
        migrations.AddField(
            model_name='uzsakymoeilute',
            name='useris',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
